/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BonnesAffairesRouteImport } from './routes/bonnes-affaires'
import { Route as CharcuterieRouteImport } from './routes/charcuterie'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as NouveautesRouteImport } from './routes/nouveautes'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as PlateauxRouteImport } from './routes/plateaux'
import { Route as PrestigeRouteImport } from './routes/prestige'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as SarfatiRouteImport } from './routes/sarfati'
import { Route as SpiritueuxRouteImport } from './routes/spiritueux'
import { Route as VinsRouteImport } from './routes/vins'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminBanderolesRouteImport } from './routes/_authenticated/admin/banderoles'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminCommandeTelephoneRouteImport } from './routes/_authenticated/admin/commande-telephone'
import { Route as AuthenticatedAdminLivraisonRouteImport } from './routes/_authenticated/admin/livraison'
import { Route as AuthenticatedAdminMediasRouteImport } from './routes/_authenticated/admin/medias'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminPromotionsRouteImport } from './routes/_authenticated/admin/promotions'
import { Route as AuthenticatedCompteEnviesRouteImport } from './routes/_authenticated/compte/envies'
import { Route as AuthenticatedCompteFavorisRouteImport } from './routes/_authenticated/compte/favoris'
import { Route as AuthenticatedAdminCommandesIndexRouteImport } from './routes/_authenticated/admin/commandes/index'
import { Route as AuthenticatedAdminCommandesIdRouteImport } from './routes/_authenticated/admin/commandes/$id'
import { Route as AuthenticatedAdminProduitsIndexRouteImport } from './routes/_authenticated/admin/produits/index'
import { Route as AuthenticatedAdminProduitsIdRouteImport } from './routes/_authenticated/admin/produits/$id'
import { Route as AuthenticatedCompteCommandesIndexRouteImport } from './routes/_authenticated/compte/commandes/index'
import { Route as AuthenticatedCompteCommandesIdRouteImport } from './routes/_authenticated/compte/commandes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BonnesAffairesRoute = BonnesAffairesRouteImport.update({
  id: '/bonnes-affaires',
  path: '/bonnes-affaires',
  getParentRoute: () => rootRouteImport,
} as any)
const CharcuterieRoute = CharcuterieRouteImport.update({
  id: '/charcuterie',
  path: '/charcuterie',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveautesRoute = NouveautesRouteImport.update({
  id: '/nouveautes',
  path: '/nouveautes',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateauxRoute = PlateauxRouteImport.update({
  id: '/plateaux',
  path: '/plateaux',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestigeRoute = PrestigeRouteImport.update({
  id: '/prestige',
  path: '/prestige',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const SarfatiRoute = SarfatiRouteImport.update({
  id: '/sarfati',
  path: '/sarfati',
  getParentRoute: () => rootRouteImport,
} as any)
const SpiritueuxRoute = SpiritueuxRouteImport.update({
  id: '/spiritueux',
  path: '/spiritueux',
  getParentRoute: () => rootRouteImport,
} as any)
const VinsRoute = VinsRouteImport.update({
  id: '/vins',
  path: '/vins',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBanderolesRoute =
  AuthenticatedAdminBanderolesRouteImport.update({
    id: '/banderoles',
    path: '/banderoles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommandeTelephoneRoute =
  AuthenticatedAdminCommandeTelephoneRouteImport.update({
    id: '/commande-telephone',
    path: '/commande-telephone',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLivraisonRoute =
  AuthenticatedAdminLivraisonRouteImport.update({
    id: '/livraison',
    path: '/livraison',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediasRoute =
  AuthenticatedAdminMediasRouteImport.update({
    id: '/medias',
    path: '/medias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPromotionsRoute =
  AuthenticatedAdminPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCompteEnviesRoute =
  AuthenticatedCompteEnviesRouteImport.update({
    id: '/envies',
    path: '/envies',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteFavorisRoute =
  AuthenticatedCompteFavorisRouteImport.update({
    id: '/favoris',
    path: '/favoris',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedAdminCommandesIndexRoute =
  AuthenticatedAdminCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommandesIdRoute =
  AuthenticatedAdminCommandesIdRouteImport.update({
    id: '/commandes/$id',
    path: '/commandes/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProduitsIndexRoute =
  AuthenticatedAdminProduitsIndexRouteImport.update({
    id: '/produits/',
    path: '/produits/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProduitsIdRoute =
  AuthenticatedAdminProduitsIdRouteImport.update({
    id: '/produits/$id',
    path: '/produits/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCompteCommandesIndexRoute =
  AuthenticatedCompteCommandesIndexRouteImport.update({
    id: '/commandes/',
    path: '/commandes/',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)
const AuthenticatedCompteCommandesIdRoute =
  AuthenticatedCompteCommandesIdRouteImport.update({
    id: '/commandes/$id',
    path: '/commandes/$id',
    getParentRoute: () => AuthenticatedCompteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bonnes-affaires': typeof BonnesAffairesRoute
  '/charcuterie': typeof CharcuterieRoute
  '/checkout': typeof CheckoutRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/plateaux': typeof PlateauxRoute
  '/prestige': typeof PrestigeRoute
  '/promotions': typeof PromotionsRoute
  '/sarfati': typeof SarfatiRoute
  '/spiritueux': typeof SpiritueuxRoute
  '/vins': typeof VinsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/banderoles': typeof AuthenticatedAdminBanderolesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/commande-telephone': typeof AuthenticatedAdminCommandeTelephoneRoute
  '/admin/livraison': typeof AuthenticatedAdminLivraisonRoute
  '/admin/medias': typeof AuthenticatedAdminMediasRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/compte/envies': typeof AuthenticatedCompteEnviesRoute
  '/compte/favoris': typeof AuthenticatedCompteFavorisRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/commandes/$id': typeof AuthenticatedAdminCommandesIdRoute
  '/admin/produits/$id': typeof AuthenticatedAdminProduitsIdRoute
  '/compte/commandes/$id': typeof AuthenticatedCompteCommandesIdRoute
  '/admin/commandes/': typeof AuthenticatedAdminCommandesIndexRoute
  '/admin/produits/': typeof AuthenticatedAdminProduitsIndexRoute
  '/compte/commandes/': typeof AuthenticatedCompteCommandesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bonnes-affaires': typeof BonnesAffairesRoute
  '/charcuterie': typeof CharcuterieRoute
  '/checkout': typeof CheckoutRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/plateaux': typeof PlateauxRoute
  '/prestige': typeof PrestigeRoute
  '/promotions': typeof PromotionsRoute
  '/sarfati': typeof SarfatiRoute
  '/spiritueux': typeof SpiritueuxRoute
  '/vins': typeof VinsRoute
  '/compte': typeof AuthenticatedCompteRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/admin/banderoles': typeof AuthenticatedAdminBanderolesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/commande-telephone': typeof AuthenticatedAdminCommandeTelephoneRoute
  '/admin/livraison': typeof AuthenticatedAdminLivraisonRoute
  '/admin/medias': typeof AuthenticatedAdminMediasRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/compte/envies': typeof AuthenticatedCompteEnviesRoute
  '/compte/favoris': typeof AuthenticatedCompteFavorisRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/commandes/$id': typeof AuthenticatedAdminCommandesIdRoute
  '/admin/produits/$id': typeof AuthenticatedAdminProduitsIdRoute
  '/compte/commandes/$id': typeof AuthenticatedCompteCommandesIdRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesIndexRoute
  '/admin/produits': typeof AuthenticatedAdminProduitsIndexRoute
  '/compte/commandes': typeof AuthenticatedCompteCommandesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/bonnes-affaires': typeof BonnesAffairesRoute
  '/charcuterie': typeof CharcuterieRoute
  '/checkout': typeof CheckoutRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/plateaux': typeof PlateauxRoute
  '/prestige': typeof PrestigeRoute
  '/promotions': typeof PromotionsRoute
  '/sarfati': typeof SarfatiRoute
  '/spiritueux': typeof SpiritueuxRoute
  '/vins': typeof VinsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/compte': typeof AuthenticatedCompteRouteWithChildren
  '/produit/$slug': typeof ProduitSlugRoute
  '/_authenticated/admin/banderoles': typeof AuthenticatedAdminBanderolesRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/commande-telephone': typeof AuthenticatedAdminCommandeTelephoneRoute
  '/_authenticated/admin/livraison': typeof AuthenticatedAdminLivraisonRoute
  '/_authenticated/admin/medias': typeof AuthenticatedAdminMediasRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/promotions': typeof AuthenticatedAdminPromotionsRoute
  '/_authenticated/compte/envies': typeof AuthenticatedCompteEnviesRoute
  '/_authenticated/compte/favoris': typeof AuthenticatedCompteFavorisRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/commandes/$id': typeof AuthenticatedAdminCommandesIdRoute
  '/_authenticated/admin/produits/$id': typeof AuthenticatedAdminProduitsIdRoute
  '/_authenticated/compte/commandes/$id': typeof AuthenticatedCompteCommandesIdRoute
  '/_authenticated/admin/commandes/': typeof AuthenticatedAdminCommandesIndexRoute
  '/_authenticated/admin/produits/': typeof AuthenticatedAdminProduitsIndexRoute
  '/_authenticated/compte/commandes/': typeof AuthenticatedCompteCommandesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bonnes-affaires'
    | '/charcuterie'
    | '/checkout'
    | '/nouveautes'
    | '/panier'
    | '/plateaux'
    | '/prestige'
    | '/promotions'
    | '/sarfati'
    | '/spiritueux'
    | '/vins'
    | '/admin'
    | '/compte'
    | '/produit/$slug'
    | '/admin/banderoles'
    | '/admin/clients'
    | '/admin/commande-telephone'
    | '/admin/livraison'
    | '/admin/medias'
    | '/admin/pages'
    | '/admin/promotions'
    | '/compte/envies'
    | '/compte/favoris'
    | '/admin/'
    | '/admin/commandes/$id'
    | '/admin/produits/$id'
    | '/compte/commandes/$id'
    | '/admin/commandes/'
    | '/admin/produits/'
    | '/compte/commandes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bonnes-affaires'
    | '/charcuterie'
    | '/checkout'
    | '/nouveautes'
    | '/panier'
    | '/plateaux'
    | '/prestige'
    | '/promotions'
    | '/sarfati'
    | '/spiritueux'
    | '/vins'
    | '/compte'
    | '/produit/$slug'
    | '/admin/banderoles'
    | '/admin/clients'
    | '/admin/commande-telephone'
    | '/admin/livraison'
    | '/admin/medias'
    | '/admin/pages'
    | '/admin/promotions'
    | '/compte/envies'
    | '/compte/favoris'
    | '/admin'
    | '/admin/commandes/$id'
    | '/admin/produits/$id'
    | '/compte/commandes/$id'
    | '/admin/commandes'
    | '/admin/produits'
    | '/compte/commandes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bonnes-affaires'
    | '/charcuterie'
    | '/checkout'
    | '/nouveautes'
    | '/panier'
    | '/plateaux'
    | '/prestige'
    | '/promotions'
    | '/sarfati'
    | '/spiritueux'
    | '/vins'
    | '/_authenticated/admin'
    | '/_authenticated/compte'
    | '/produit/$slug'
    | '/_authenticated/admin/banderoles'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/commande-telephone'
    | '/_authenticated/admin/livraison'
    | '/_authenticated/admin/medias'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/promotions'
    | '/_authenticated/compte/envies'
    | '/_authenticated/compte/favoris'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/commandes/$id'
    | '/_authenticated/admin/produits/$id'
    | '/_authenticated/compte/commandes/$id'
    | '/_authenticated/admin/commandes/'
    | '/_authenticated/admin/produits/'
    | '/_authenticated/compte/commandes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  BonnesAffairesRoute: typeof BonnesAffairesRoute
  CharcuterieRoute: typeof CharcuterieRoute
  CheckoutRoute: typeof CheckoutRoute
  NouveautesRoute: typeof NouveautesRoute
  PanierRoute: typeof PanierRoute
  PlateauxRoute: typeof PlateauxRoute
  PrestigeRoute: typeof PrestigeRoute
  PromotionsRoute: typeof PromotionsRoute
  SarfatiRoute: typeof SarfatiRoute
  SpiritueuxRoute: typeof SpiritueuxRoute
  VinsRoute: typeof VinsRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonnes-affaires': {
      id: '/bonnes-affaires'
      path: '/bonnes-affaires'
      fullPath: '/bonnes-affaires'
      preLoaderRoute: typeof BonnesAffairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charcuterie': {
      id: '/charcuterie'
      path: '/charcuterie'
      fullPath: '/charcuterie'
      preLoaderRoute: typeof CharcuterieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveautes': {
      id: '/nouveautes'
      path: '/nouveautes'
      fullPath: '/nouveautes'
      preLoaderRoute: typeof NouveautesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plateaux': {
      id: '/plateaux'
      path: '/plateaux'
      fullPath: '/plateaux'
      preLoaderRoute: typeof PlateauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestige': {
      id: '/prestige'
      path: '/prestige'
      fullPath: '/prestige'
      preLoaderRoute: typeof PrestigeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sarfati': {
      id: '/sarfati'
      path: '/sarfati'
      fullPath: '/sarfati'
      preLoaderRoute: typeof SarfatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spiritueux': {
      id: '/spiritueux'
      path: '/spiritueux'
      fullPath: '/spiritueux'
      preLoaderRoute: typeof SpiritueuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vins': {
      id: '/vins'
      path: '/vins'
      fullPath: '/vins'
      preLoaderRoute: typeof VinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/banderoles': {
      id: '/_authenticated/admin/banderoles'
      path: '/banderoles'
      fullPath: '/admin/banderoles'
      preLoaderRoute: typeof AuthenticatedAdminBanderolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commande-telephone': {
      id: '/_authenticated/admin/commande-telephone'
      path: '/commande-telephone'
      fullPath: '/admin/commande-telephone'
      preLoaderRoute: typeof AuthenticatedAdminCommandeTelephoneRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/livraison': {
      id: '/_authenticated/admin/livraison'
      path: '/livraison'
      fullPath: '/admin/livraison'
      preLoaderRoute: typeof AuthenticatedAdminLivraisonRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/medias': {
      id: '/_authenticated/admin/medias'
      path: '/medias'
      fullPath: '/admin/medias'
      preLoaderRoute: typeof AuthenticatedAdminMediasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promotions': {
      id: '/_authenticated/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AuthenticatedAdminPromotionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/compte/envies': {
      id: '/_authenticated/compte/envies'
      path: '/envies'
      fullPath: '/compte/envies'
      preLoaderRoute: typeof AuthenticatedCompteEnviesRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/favoris': {
      id: '/_authenticated/compte/favoris'
      path: '/favoris'
      fullPath: '/compte/favoris'
      preLoaderRoute: typeof AuthenticatedCompteFavorisRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/admin/commandes/': {
      id: '/_authenticated/admin/commandes/'
      path: '/commandes'
      fullPath: '/admin/commandes/'
      preLoaderRoute: typeof AuthenticatedAdminCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commandes/$id': {
      id: '/_authenticated/admin/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/admin/commandes/$id'
      preLoaderRoute: typeof AuthenticatedAdminCommandesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produits/': {
      id: '/_authenticated/admin/produits/'
      path: '/produits'
      fullPath: '/admin/produits/'
      preLoaderRoute: typeof AuthenticatedAdminProduitsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/produits/$id': {
      id: '/_authenticated/admin/produits/$id'
      path: '/produits/$id'
      fullPath: '/admin/produits/$id'
      preLoaderRoute: typeof AuthenticatedAdminProduitsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/compte/commandes/': {
      id: '/_authenticated/compte/commandes/'
      path: '/commandes'
      fullPath: '/compte/commandes/'
      preLoaderRoute: typeof AuthenticatedCompteCommandesIndexRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
    '/_authenticated/compte/commandes/$id': {
      id: '/_authenticated/compte/commandes/$id'
      path: '/commandes/$id'
      fullPath: '/compte/commandes/$id'
      preLoaderRoute: typeof AuthenticatedCompteCommandesIdRouteImport
      parentRoute: typeof AuthenticatedCompteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBanderolesRoute: typeof AuthenticatedAdminBanderolesRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminCommandeTelephoneRoute: typeof AuthenticatedAdminCommandeTelephoneRoute
  AuthenticatedAdminLivraisonRoute: typeof AuthenticatedAdminLivraisonRoute
  AuthenticatedAdminMediasRoute: typeof AuthenticatedAdminMediasRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPromotionsRoute: typeof AuthenticatedAdminPromotionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCommandesIdRoute: typeof AuthenticatedAdminCommandesIdRoute
  AuthenticatedAdminProduitsIdRoute: typeof AuthenticatedAdminProduitsIdRoute
  AuthenticatedAdminCommandesIndexRoute: typeof AuthenticatedAdminCommandesIndexRoute
  AuthenticatedAdminProduitsIndexRoute: typeof AuthenticatedAdminProduitsIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBanderolesRoute: AuthenticatedAdminBanderolesRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminCommandeTelephoneRoute:
    AuthenticatedAdminCommandeTelephoneRoute,
  AuthenticatedAdminLivraisonRoute: AuthenticatedAdminLivraisonRoute,
  AuthenticatedAdminMediasRoute: AuthenticatedAdminMediasRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPromotionsRoute: AuthenticatedAdminPromotionsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCommandesIdRoute: AuthenticatedAdminCommandesIdRoute,
  AuthenticatedAdminProduitsIdRoute: AuthenticatedAdminProduitsIdRoute,
  AuthenticatedAdminCommandesIndexRoute: AuthenticatedAdminCommandesIndexRoute,
  AuthenticatedAdminProduitsIndexRoute: AuthenticatedAdminProduitsIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCompteRouteChildren {
  AuthenticatedCompteEnviesRoute: typeof AuthenticatedCompteEnviesRoute
  AuthenticatedCompteFavorisRoute: typeof AuthenticatedCompteFavorisRoute
  AuthenticatedCompteCommandesIdRoute: typeof AuthenticatedCompteCommandesIdRoute
  AuthenticatedCompteCommandesIndexRoute: typeof AuthenticatedCompteCommandesIndexRoute
}

const AuthenticatedCompteRouteChildren: AuthenticatedCompteRouteChildren = {
  AuthenticatedCompteEnviesRoute: AuthenticatedCompteEnviesRoute,
  AuthenticatedCompteFavorisRoute: AuthenticatedCompteFavorisRoute,
  AuthenticatedCompteCommandesIdRoute: AuthenticatedCompteCommandesIdRoute,
  AuthenticatedCompteCommandesIndexRoute:
    AuthenticatedCompteCommandesIndexRoute,
}

const AuthenticatedCompteRouteWithChildren =
  AuthenticatedCompteRoute._addFileChildren(AuthenticatedCompteRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCompteRoute: AuthenticatedCompteRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  BonnesAffairesRoute: BonnesAffairesRoute,
  CharcuterieRoute: CharcuterieRoute,
  CheckoutRoute: CheckoutRoute,
  NouveautesRoute: NouveautesRoute,
  PanierRoute: PanierRoute,
  PlateauxRoute: PlateauxRoute,
  PrestigeRoute: PrestigeRoute,
  PromotionsRoute: PromotionsRoute,
  SarfatiRoute: SarfatiRoute,
  SpiritueuxRoute: SpiritueuxRoute,
  VinsRoute: VinsRoute,
  ProduitSlugRoute: ProduitSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
